services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  server:
    build: .
    volumes:
      - .:/app
    command: bms-sim-server mqtt://broker/bms_sim
    depends_on:
      - broker
